import { AiUnavailableError, type AIService, type DocumentAnalysisRequest, type MatchExplanationRequest } from './AIService';
import { parseAiAnalysis, toAnalysisResult } from './validation';
import type { DocumentAnalysisResult } from '@/types';

const GROQ_ENDPOINT = 'https://api.groq.com/openai/v1/chat/completions';
const DEFAULT_MODEL = 'llama-3.3-70b-versatile';
const TIMEOUT_MS = 12_000;

const SYSTEM_PROMPT = `You are a document pre-screening assistant inside a scholarship prototype.
You never decide eligibility, never reject a student and never promise a selection.
You only describe what a document appears to contain and flag observations for a human reviewer.

Return STRICT JSON only, with this exact shape:
{
  "documentType": one of the offered document types,
  "confidence": number between 0 and 1,
  "fields": { "name": string|null, "income": string|number|null, "financialYear": string|null, "institution": string|null, "course": string|null, "certificateType": string|null, "issuingAuthority": string|null, "issueDate": string|null, "expiryDate": string|null, "documentNumber": string|null },
  "findings": [ { "type": one of DOCUMENT_CLASSIFICATION|FIELD_EXTRACTION|NAME_VARIATION|MISSING_FIELD|POSSIBLE_EXPIRY|CONSISTENCY_CHECK, "severity": one of INFO|WARNING|HIGH, "message": string, "confidence": number|null } ]
}

Rules:
- Use only what is readable in the file name and any text provided. Never guess values.
- If a value is not readable, use null and add a MISSING_FIELD finding.
- Use at most 6 findings. Keep every message under 220 characters.
- Never include an Aadhaar, PAN or bank account number in any field or message.
- If the file is unreadable, return documentType "OTHER" with low confidence.`;

function apiKey(): string | null {
  const value = process.env.GROQ_API_KEY?.trim();
  return value ? value : null;
}

export class GroqAIService implements AIService {
  readonly provider = 'GROQ' as const;

  isConfigured(): boolean {
    return apiKey() !== null;
  }

  private async complete(prompt: string, maxTokens = 700): Promise<string> {
    const key = apiKey();
    if (!key) throw new AiUnavailableError('GROQ_API_KEY is not configured.');

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
    try {
      const response = await fetch(GROQ_ENDPOINT, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${key}`,
        },
        body: JSON.stringify({
          model: process.env.GROQ_MODEL?.trim() || DEFAULT_MODEL,
          temperature: 0.1,
          max_tokens: maxTokens,
          response_format: { type: 'json_object' },
          messages: [
            { role: 'system', content: SYSTEM_PROMPT },
            { role: 'user', content: prompt },
          ],
        }),
        signal: controller.signal,
      });

      if (!response.ok) {
        const body = await response.text().catch(() => '');
        throw new AiUnavailableError(`Groq responded with ${response.status}. ${body.slice(0, 200)}`);
      }

      const json = (await response.json()) as {
        choices?: { message?: { content?: string } }[];
      };
      const content = json.choices?.[0]?.message?.content;
      if (!content) throw new AiUnavailableError('Groq returned an empty response.');
      return content;
    } catch (error) {
      if (error instanceof AiUnavailableError) throw error;
      const message = error instanceof Error ? error.message : 'Unknown error';
      throw new AiUnavailableError(`Groq request failed: ${message}`);
    } finally {
      clearTimeout(timer);
    }
  }

  async analyzeDocument(request: DocumentAnalysisRequest): Promise<DocumentAnalysisResult> {
    const typeList = request.expectedTypes.map((item) => `- ${item.type}: ${item.label}`).join('\n');
    const prompt = [
      `File name: ${request.fileName}`,
      `MIME type: ${request.mimeType}`,
      `Document type selected by the student: ${request.selectedType ?? 'not selected'}`,
      `Name typed by the student for this document: ${request.declaredName ?? 'not provided'}`,
      `Additional text: ${request.textHint ?? 'none'}`,
      `Applicant name in profile: ${request.profile.fullName}`,
      `Institution in profile: ${request.profile.institution ?? 'not provided'}`,
      `Course in profile: ${request.profile.course ?? 'not provided'}`,
      `Annual family income in profile: ${request.profile.annualFamilyIncome ?? 'not provided'}`,
      '',
      'Candidate document types:',
      typeList,
    ].join('\n');

    const raw = await this.complete(prompt);
    const payload = parseAiAnalysis(raw, request.fileName);
    return toAnalysisResult(payload, 'GROQ', request.fileName, {
      note: 'Pre-screening observation generated by Groq. A reviewing officer makes the final decision.',
    });
  }

  async explainMatch(request: MatchExplanationRequest): Promise<string | null> {
    const prompt = [
      `Scheme: ${request.schemeName}`,
      `Aletheia match status: ${request.status}`,
      'Conditions evaluated deterministically:',
      ...request.conditions.map((c) => `- ${c.label} [${c.outcome}]: ${c.detail}`),
      `Documents available: ${request.readiness.availableCount} of ${request.readiness.requiredCount}`,
      `Documents still needed: ${request.readiness.missing.join(', ') || 'none'}`,
      '',
      'Explain this to a student in 2-3 short sentences. Do not add any rule, amount or deadline that is not stated above, and do not predict a selection outcome.',
    ].join('\n');

    try {
      const raw = await this.complete(prompt, 300);
      return raw.trim().replace(/^["']|["']$/g, '') || null;
    } catch {
      return null;
    }
  }
}
